# Generated by Django 5.2 on 2025-08-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('logistic_user_lvl1', 'Logistic User Level 1'), ('logistic_user_lvl2', 'Logistic User Level 2'), ('logistic_manager', 'Logistic Manager'), ('warehouse_user_lvl1', 'Warehouse User Level 1'), ('warehouse_user_lvl2', 'Warehouse User Level 2'), ('warehouse_manager', 'Warehouse Manager'), ('general_manager', 'General Manager')], max_length=30)),
                ('id_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
