# Generated by Django 5.2 on 2025-07-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('land', 'Land'), ('naval', 'Naval'), ('air', 'Air')], max_length=10)),
                ('from_T', models.CharField(max_length=50)),
                ('to_T', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('cargo', 'Cargo'), ('personnel', 'Personnel'), ('military', 'Military')], max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('capacity_unit', models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('pers', 'Persons'), ('units', 'Units')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirTransport',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LogisticManager.transport')),
                ('available', models.BooleanField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.route')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.transporttype')),
            ],
            bases=('LogisticManager.transport',),
        ),
        migrations.CreateModel(
            name='LandTransport',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LogisticManager.transport')),
                ('available', models.BooleanField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.route')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.transporttype')),
            ],
            bases=('LogisticManager.transport',),
        ),
        migrations.CreateModel(
            name='NavalTransport',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LogisticManager.transport')),
                ('available', models.BooleanField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.route')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogisticManager.transporttype')),
            ],
            bases=('LogisticManager.transport',),
        ),
    ]
