# Generated by Django 5.2 on 2025-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogisticManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='unit',
            field=models.CharField(blank=True, default='Km', max_length=10),
        ),
    ]
