# Generated by Django 4.2.6 on 2023-10-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManager', '0004_alter_cartransport_cartransporttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_T', models.CharField(max_length=50)),
                ('to_T', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Naval_routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_T', models.CharField(max_length=50)),
                ('to_T', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cartransport',
            name='Route',
            field=models.CharField(choices=[('a', 'a')], max_length=100),
        ),
        migrations.AlterField(
            model_name='navaltransport',
            name='Route',
            field=models.CharField(choices=[('a', 'a')], max_length=100),
        ),
    ]
