# Generated by Django 4.2.6 on 2023-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManager', '0005_car_routes_naval_routes_alter_cartransport_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartransport',
            name='Route',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='navaltransport',
            name='Route',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
